"""Adicionar suporte a variações de produtos com cor e tamanho

Revision ID: a6ddaa3a9f1d
Revises: 5abee7c9919d
Create Date: 2026-07-28 10:50:20.922179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ddaa3a9f1d'
down_revision: Union[str, Sequence[str], None] = '5abee7c9919d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_variacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('tamanho', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_variacoes_id'), 'produto_variacoes', ['id'], unique=False)
    
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_variacao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('produto_variacao_descricao', sa.String(length=150), nullable=True))
        batch_op.create_foreign_key('fk_itens_venda_produto_variacao_id', 'produto_variacoes', ['produto_variacao_id'], ['id'], ondelete='SET NULL')
    
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_variacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_movimentacoes_produto_variacao_id', 'produto_variacoes', ['produto_variacao_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('estoque_atual')
        batch_op.drop_column('preco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('estoque_atual', sa.INTEGER(), nullable=False))
    
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacoes_produto_variacao_id', type_='foreignkey')
        batch_op.drop_column('produto_variacao_id')
    
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itens_venda_produto_variacao_id', type_='foreignkey')
        batch_op.drop_column('produto_variacao_descricao')
        batch_op.drop_column('produto_variacao_id')
    
    op.drop_index(op.f('ix_produto_variacoes_id'), table_name='produto_variacoes')
    op.drop_table('produto_variacoes')
    # ### end Alembic commands ###
